version: '3.8'
services:
  web:
    build: .
    container_name: web_app
    volumes:
      - ./app:/var/www/html
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./backup:/backup
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:
